# Generated by Django 3.2 on 2022-01-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='defalt_street_address1',
            new_name='default_street_address1',
        ),
    ]
