# Generated by Django 3.2 on 2022-02-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('position', models.CharField(max_length=254)),
                ('rank', models.CharField(max_length=254)),
                ('bio', models.TextField()),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('image', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
    ]
