# Generated by Django 3.2 on 2022-02-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='awards',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='coach',
            name='position',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
