# Generated by Django 3.2 on 2022-03-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_coach_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='classes',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
